created getCart, changed Cart model to CartRow
techsweave/eml-be pull request #24
Opened 2021-04-25 14:31 UTC by samupd2013

2021-04-25 14:33 UTC, Manuv46 approved these changes

2021-04-25 14:39 UTC, amemeggio approved these changes

2021-04-25 15:23 UTC, URBA22 requested changes

2021-04-25 15:23 UTC, URBA22 commented on src/functions/carts/getCart/handler.ts
> +    let response: Response<CartRow[]>;
Write here only CartRow, without []

2021-04-25 15:23 UTC, URBA22 commented on src/functions/carts/getCart/handler.ts
> +        response = Response.fromData<CartRow[]>(cart, HttpStatusCodes.OK);
There is a factory method `fromMultipleData`

2021-04-25 15:23 UTC, URBA22 commented on src/functions/carts/getCart/handler.ts
> +        for await (const element of dbContext.scan(CartRow)) {
Pay attention to pagination, see [https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html), section 'Paginating the Results'.
I suggest to use array `concat` method to store the page.
For example see the the function scanProduct.

2021-04-26 14:51 UTC, URBA22 approved these changes

2021-04-26 14:51 UTC, merged