created deleteProduct lambda
techsweave/eml-be pull request #33
Opened 2021-05-10 13:23 UTC by samupd2013

2021-05-10 14:18 UTC, URBA22 approved these changes

2021-05-10 14:20 UTC, URBA22 commented
Funcion `dbContext.delete` returns the eliminated element right?

2021-05-10 14:22 UTC, samupd2013 commented
yes, i locally testet the function and it returned the element

2021-05-10 14:23 UTC, Manuv46 approved these changes

2021-05-10 14:24 UTC, Manuv46 approved these changes

2021-05-10 16:56 UTC, URBA22 requested changes

2021-05-10 16:56 UTC, URBA22 commented on src/functions/products/deleteProduct/index.ts
> +                method: 'post',
Http method is `delete`

2021-05-11 08:25 UTC, URBA22 approved these changes

2021-05-11 09:02 UTC, merged