created updateProduct lamba function
techsweave/eml-be pull request #35
Opened 2021-05-10 15:45 UTC by samupd2013

2021-05-10 16:58 UTC, URBA22 requested changes

2021-05-10 16:58 UTC, URBA22 commented on src/functions/products/updateProduct/index.ts
> +                path: 'products/{id}/edit',
Use the path `products/{id}` and the http method `put`

2021-05-12 07:31 UTC, URBA22 approved these changes

2021-05-12 10:48 UTC, Manuv46 approved these changes

2021-05-12 10:50 UTC, merged